# parameters
class_number: 10 # number of classes

backbone:
  # [from, number, module, args]
  [
    [ -1, 1, nn.Conv2d, [ 3, 16, 3, 1, 1 ] ],
    [ -1, 1, nn.ReLU, [] ],
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],

    [ -1, 1, nn.Conv2d, [ 16, 32, 3, 1, 1 ] ],
    [ -1, 1, nn.ReLU, [] ],
    [ -1, 1, nn.MaxPool2d, [ 2 ] ]
  ]

head:
  [
    [ -1, 1, nn.Flatten, []],
    [ -1, 1, nn.Linear, [ 32 * 8 * 8, 128 ] ],
    [ -1, 1, nn.Linear, [ 128, 10 ] ]
  ]