umap_args_2d:
  "n_neighbors": 15
  "min_dist": 0.1
  "n_components": 2
  "random_state": 1111
  "metric": "euclidean"

umap_args_3d:
  "n_neighbors": 15
  "min_dist": 0.1
  "n_components": 3
  "random_state": 1111
  "metric": "euclidean"

hdbscan_args:
  "min_cluster_size": 100
  "min_samples": 1
  "cluster_selection_method": "eom"
  "cluster_selection_epsilon": 0.5
  "metric": "euclidean"
  "prediction_data": True

hac_args:
  "n_clusters": 100
  "metric": "cosine"
  "connectivity": "pairwise"

kmeans_args:
  # Euclidean should be ok
  # Normalize first? Becomes approximation of cosine
  "n_clusters": 1024
  # Number of instances the k-means algorithm will be called with different seeds.
  # The final results will be from the instance that produces lowest inertia out of n_init instances.
  "n_init": 10