umap_args:
  "n_neighbors": 15
  "min_dist": 0.0
  "n_components": 2
  "random_state": 42069
  "metric": "euclidean"


hdbscan_args:
  "min_cluster_size": 5
  "min_samples": 1
  "cluster_selection_method": "eom"
  "cluster_selection_epsilon": 0.5
  "metric": "manhattan"

hac_args:
  "n_clusters": 10
  "metric": "euclidean"

kmeans_args:
  "n_clusters": 10