clustering:
  kmeans:
    k_start: 400
    k_end: 1100
    k_step: 50
  hdbscan:
    min_samples: [ 1, 3, 5, 10, 25, 50, 75, 100 ]
    min_cluster_size: [ 5, 10, 25, 60, 100 ]
    # If you are more interested in having small homogeneous clusters, then you may find Excess of Mass has a tendency
    # to pick one or two large clusters and then a number of small extra clusters. In this situation you may be tempted
    # to recluster just the data in the single large cluster. Instead, a better option is to select 'leaf' as a cluster selection method.
    cluster_selection_method: [ eom, leaf ]
    # In some cases, we want to choose a small min_cluster_size because even groups of few points might be of interest.
    # However, if our data set also contains partitions with high concentrations of objects, this parameter setting can
    # result in a large number of micro-clusters. Selecting a value for cluster_selection_epsilon helps us to merge
    # clusters in these regions. Or in other words, it ensures that clusters below the given threshold are not split up any further.
    cluster_selection_epsilon: [0.0, 0.5]
    metric: [ euclidean, manhattan, infinity ]
  hac:
    "n_clusters": 10
    "metric": "euclidean"